football_result/config/routes.rb
Rails.application.routes.draw do
=begin
   get 'posts' => 'posts#index'
   get 'posts/new' => 'posts#new'
   post 'posts' => 'posts#create'
   get 'posts/:id' => 'posts#show'
   get 'posts/:id/edit' => 'posts#edit'
   put 'posts/:id' => 'posts#update'
   delete 'posts/:id' => 'posts#destroy'
=end


   resources :posts do
     resources :comments, only: [:create, :destroy]
   end
end

football_result/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :post, presence: true
  validates :name, presence: true
  validates :content, presence: true, length: { in: 1..1000 }
end

football_result/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :hometeam, presence: true
  validates :awayteam, presence: true
  validates :hr, presence: true
  validates :ar, presence: true


end

football_result/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
end

football_result/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
    @data = Post.find(params[:post_id])
    @comment = Comment.new(params_comment)
    @comment.post = @data

    if @comment.save
      redirect_to post_url(@data)
    else
      render "posts/show"
    end
  end


 def destroy
    @data = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_url(@data)
  end

  private

  def params_comment
    params.require(:comment).permit(:name, :content)
  end

end

football_result/app/controllers/createpath_to_Railsapp.rb
def create_all_image_name
    all_image_name = []
    Dir.glob("/Users/yokooannosuke/Cording/Rails_developmet/football_result/app/assets/images/*.png").each do |em|
      images_name = File.basename(em)
      all_image_name.push(images_name)
    end
    return  all_image_name
end



def create_default_hassyu(name1)
  default_name = { "アーセナル"=>"Arsenal",  "アストン・ヴィラ"=>"AstonVilla","ブライトン"=>'BrightonandHoveAlbion',
    "バーンリー"=>'Burnley',"チェルシー"=>'Chelsea',"クリスタルパレス"=>'CrystalPalace',"エバートン"=>'Everton',"フラム"=>'Fulham',"リーズ"=>'LeedsUnited',
    "レスター"=>'LeicesterCity',"リバプール"=>'Liverpool',"マンチェスターシティ"=>'ManchesterCity',"マンチェスターユナテッド"=>'ManchesterUnited',"ニューカッスル"=>'NewcastleUnited',
    "シェフィールド"=>'SheffieldUnited', "サウサウプトン"=>'Southampton', "トッテナム"=>'TottenhamHotspur',
    "ウェストブロムウィッチ"=>'WestBromwichAlbion',"ウェストハム"=>'WestHamUnited',"ウォルバーハンプトン"=>'WolverhamptonWanderers'}
  default_hassyu = default_name.find{|key,value| key == name1 }
  return default_hassyu
end

def create_other_hassyu(name2)
  other_name = {"アストン・ヴィラ"=>"AstonVilla","アストンヴィラ"=>"AstonVilla","フルアム"=>'Fulham',"マンチェスターC"=>'ManchesterCity',
    "マンC"=>'ManchesterCity',"マンシティ"=>'ManchesterCity',"マンU"=>"ManchesterUnited","マンチェスターU"=>"ManchesterUnited",
    "シェフィールドU"=>'SheffieldUnited', "スパーズ"=>'TottenhamHotspur',"WBA"=>'WestBromwichAlbion',
    "ウエストハム" =>'WestHamUnited',"ウェストブロムウィッチアルビオン"=>'WestBromwichAlbion',"ウルブス"=>'WolverhamptonWanderers', "ウルバーハンプトン"=>'WolverhamptonWanderers'}
  other_hassyu = other_name.find{|key,value| key == name2}
  return other_hassyu
end

def search_team(team_list,name1,name2) #name1 , name2は　フォームから受けとるカタカナのチーム名

  if create_default_hassyu(name1) != nil
    home_png = create_default_hassyu(name1)[1] + ".png"
  else
    if create_other_hassyu(name1) != nil
      home_png = create_other_hassyu(name1)[1] + ".png"
    else
      home_png = nil
      puts("入力したホームチーム名は見つかりませんでした。")
    end
  end

  if create_default_hassyu(name2) != nil
    away_png = create_default_hassyu(name2)[1] + ".png"
  else
    if create_other_hassyu(name2) != nil
      away_png = create_other_hassyu(name2)[1] + ".png"
    else
      away_png = nil
      puts("入力したアウェイチーム名は見つかりませんでした。")
    end
  end

  home_em_png = team_list.find {|item1| item1 == home_png }
  away_em_png = team_list.find {|item2| item2 == away_png }

  return home_em_png , away_em_png

end



puts search_team( create_all_image_name , "マンU", "アセナル" )

football_result/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @data = Post.all

  end

  def show
    @data = Post.includes(:comments).find(params[:id])
    @comment = Comment.new
  end

  def new
    @data = Post.new
  end

  def create
    @data = Post.new(params_post)
    @data.save
    goindex
  end

  def edit
    @data = Post.find(params[:id])
  end

  def update
    @data = Post.find(params[:id])
    @data.update_attributes(params_post)
    goindex
   end

  def destroy
    @data = Post.find(params[:id])
    @data.destroy
    goindex
  end


  private

  def params_post
    params.permit(:hometeam, :awayteam, :hr, :ar,:MyMOM, :memo, :date)
  end

  def goindex
    redirect_to "/posts"
  end




end

football_result/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>FootballResult</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css"><!-- Bootstrap の読み込み-->

  </head>

  <body　class = "container">
    <div id="layout">
      <%= yield %>
    </div>
  </body>
</html>

football_result/app/views/posts/edit.html.erb
<div class = "top">
    <h1 class="display-4 text-primary">Posts#edit</h1>
    <p class="title">試合詳細<a href="/posts" class="btn btn-primary btn-xs">試合結果一覧に戻る</a></p>
</div>


<%=form_tag "/posts/#{@data.id}", method: :put do %>
<div class="row">
    <div class="date">
        <div class="form-group">
            <div class="col-md-16">
                <label for="date">Macth_Day</label><br>
                <%= date_field_tag(:date,"#{@data.date}", {class:"form-control"}) %>
            </div>
        </div>
    </div>
    <div class="home-form">
        <div class="form-group">
            <div class="col-md-16">
                <label for="hometeam">Hometeam</label>
                <%= text_field_tag(:hometeam,"#{@data.hometeam}", {class:"form-control"}) %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-16">
                <label for="hr">H.得点</label>
                <%= number_field_tag(:hr,"#{@data.hr}",  in: 0..10, step: 1 , class:"form-control")  %>
            </div>
        </div>
    </div>
    <div class="away-form">
        <div class="form-group">
            <div class="col-md-16">
                <label for="ar">A.得点</label>
                <%= number_field_tag(:ar,"#{@data.ar}",  in: 0..10, step: 1 , class:"form-control") %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-16">
                <label for="awayteam">Awayteam</label>
                <%= text_field_tag(:awayteam,"#{@data.awayteam}", {class:"form-control"}) %>
            </div>
        </div>
    </div>
</div>

<div class="kannsou-form">
    <h3 class="section-title">感想メモ</h3>
    <label for="MyMOM">MyMOM &#x1f451;</label>
    <%= text_field_tag(:MyMOM,"#{@data.MyMOM}", {class:"form-control"}) %>
    <label for="memo">試合メモ</label>
    <%= text_area_tag(:memo,"#{@data.memo}",{class:"form-control"}) %>
    <%= submit_tag("保存",  {class: "btn-primary btn-lg"}) %>
</div>


<% end %>

football_result/app/views/posts/index.html.erb
<div class = "top">
    <h1 class="display-4 text-primary">Posts#index</h1>
    <p class="title">試合結果一覧<a href="/posts/new" class="btn btn-primary btn-lg">新規投稿</a></p>
</div>

<table class="table"  >
    <tr  >
        <th>Match_Id</th>
        <th>Macth_Day</th>
        <th>Home-team</th>
        <th>Match_result</th>
        <th>Away-team</th>
        <th></th>
    </tr>
    <% @data.each do |obj| %>
    <tr>
        <% require "./app/controllers/createpath_to_Railsapp.rb" #createpath_to_Railsapp を読み込み%>
        <% team_array = create_all_image_name %>
        <% home_png , away_png = search_team(team_array, obj.hometeam ,obj.awayteam)%>

        <td class= "move-right"><a href="/posts/<%= obj.id%>">　<%= obj.id %></a></td>
        <td><%= obj.date %></td>
        <td><%= obj.hometeam %>
            <% if home_png != nil %>
                <%= image_tag  home_png , :size => "25x25" %>
            <% end %>
        </td>
        <td class="move-right">　　<%= obj.hr %> <span>-</span> <%= obj.ar %></td>
        <td><%= obj.awayteam %>
            <% if away_png != nil %>
                <%= image_tag away_png , :size =>'25x25' %>
            <% end %>
        </td>
        <td><%= link_to "Edit", "/posts/#{obj.id}/edit" %>　<%= link_to "Delete", "/posts/#{obj.id}", method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
    </tr>
    <% end %>
</table>

football_result/app/views/posts/new.html.erb
<h1 class="display-4 text-primary">Posts#new</h1>

<%=form_tag "/posts", method: :post do %>
    <div class="row">
        <div class="date">
            <div class = "form-group">
                <div class="col-md-16">
                    <label for="date">Macth_Day</label><br>
                    <%= date_field_tag(:date,"", {class:"form-control"}) %>
                </div>
            </div>
        </div>
        <div class="home-form">
            <div class="form-group">
                <div class="col-md-16">
                    <label for="hometeam">Hometeam</label>
                    <%= text_field_tag(:hometeam,"", {class:"form-control"}) %>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-16">
                    <label for="hr">H.得点</label>
                    <%= number_field_tag(:hr,"",  in: 0..10, step: 1 , class:"form-control")  %>
                </div>
            </div>
        </div>
        <div class = "away-form">
            <div class="form-group">
                <div class="col-md-16">
                    <label for="ar">A.得点</label>
                    <%= number_field_tag(:ar,"",  in: 0..10, step: 1 , class:"form-control") %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-16">
                    <label for="awayteam">Awayteam</label>
                    <%= text_field_tag(:awayteam,"", {class:"form-control"}) %>
                </div>
            </div>
        </div>
    </div>

    <div class="kannsou-form">
        <h3 class="section-title">感想メモ</h3>
        <label for="MyMOM">MyMOM &#x1f451;</label>
        <%= text_field_tag(:MyMOM,"", {class:"form-control"}) %>
        <label for="memo">試合メモ</label>
        <%= text_area_tag(:memo,"",{class:"form-control"}) %>
    </div>
    <%= submit_tag("投稿",  {class: "btn-primary btn-lg"}) %>

<% end %>
<br>
<%= link_to "試合結果一覧に戻る", "/posts" %>

football_result/app/views/posts/show.html.erb
<div class = "top">
    <h1 class="display-4 text-primary">Posts#show</h1>
    <p class="title">試合詳細<a href="/posts" class="btn btn-primary btn-lg>試合結果一覧に戻る</a></p>
</div>

<div class = "menu">
    <%= link_to "Edit", "/posts/#{@data.id}/edit" %>
    <%= link_to "Delete", "/posts/#{@data.id}", method: :get, data: { confirm: "本当に削除しますか？" } %>
</div>

<table class="table">
    <tr> <!-- 表の横一行-->
        <th>Match_Id</th><!-- th: table header-->
        <th>Match_Day
        <th>Hometeam</th>
        <th>Match_result</th>
        <th>Awayteam</th>
    </tr>
    <tr>
       <% require "./app/controllers/createpath_to_Railsapp.rb" #createpath_to_Railsapp を読み込み%>
       <% team_array = create_all_image_name %>
       <% home_png , away_png = search_team(team_array, @data.hometeam,  @data.awayteam)%>

       <td class="move-right"><a href="/posts/<%= @data.id%>">　<%= @data.id %></a></td>
       <td><%= @data.date %></td>
       <td><%= @data.hometeam %>
           <% if home_png != nil %>
           <%= image_tag  home_png , :size => "25x25" %>
           <% end %>
       </td>
       <td class="move-right">　　<%= @data.hr %> <span>-</span> <%= @data.ar %></td>
       <td><%= @data.awayteam %>
           <% if away_png != nil %>
           <%= image_tag away_png , :size =>'25x25' %>
           <% end %>
       </td>

    </tr>
</table>


<div class="kannsou-form">
    <h3 class="kannsou-title">感想メモ</h3>
    <p>MyMOM　&#x1f451;</p>
    <p class = "mom-form"><%= @data.MyMOM %> </p>
    </div>
    <p>試合メモ</p>
    <p class  = "memo-form"><%= @data.memo%></p>

</div>


 <div class="comments-index">
    <h3 class = "comments-view">コメント一覧</h3>
    <% @data.comments.each do |comment| %>
        <%= comment.name %>　:　<%= comment.content %>
        <%= link_to "削除する", post_comment_path(@data, comment), method: :delete, data: { confirm: "本当に削除しますか?" } %><br>
    <% end %>
 </div>

<div class = "comments-form">
    <h3 class="comments-title">コメント</h3>
    <%= form_for @comment, url: post_comments_path(@data, @comment) do |f| %>
        名前: <%= f.text_field :name , {class:"form-control"} %> <br>
        コメント: <%= f.text_area :content , {class:"form-control"} %>
        <%= f.submit("コメントする" ,class: 'btn btn-primary btn-lg my-1 mb-5 px-5') %>
    <% end %>
</div>